# Generated by Django 6.0.7 on 2026-07-20 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_math_teacher_website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='WaitingList',
        ),
    ]
